version: '3'

tasks:
  up:
    desc: Builds end to end an ASEv3 Internal environment
    cmds:
    - task: init
    - task: apply

  init: 
    desc: Initializes Terraform
    cmds:
    - terraform workspace new {{.APP_NAME}} || true
    - terraform workspace select {{.APP_NAME}}
    - terraform init
    vars:
      APP_NAME: '{{default .CLI_ARGS}}'

  apply: 
    desc: Applies Terraform configuration
    cmds:
    - terraform apply -auto-approve -var "ase_app_name={{.APP_NAME}}"
    vars:
      APP_NAME: '{{default .CLI_ARGS}}'

  plan:
    desc: Reviews Terraform plan
    cmds:
    - terraform plan -var "ase_app_name={{.APP_NAME}}"
    vars:
      APP_NAME: '{{default .CLI_ARGS}}'
    
  down:
    desc: Destroys all Azure resources and cleans up terraform
    cmds:
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - az group delete -n {{.RG}} --yes || true
    vars:
      RG: 
        sh: terraform output -raw RESOURCE_GROUP
