#
# Module manifest for module 'bjd.Azure.Functions'
# Generated by: Brian Denicola
# Generated on: 6/10/2020
#

@{

    RootModule = 'bjd.Azure.Functions.psm1'
    ModuleVersion = '1.0.5'
    GUID = 'c2602a90-dd9a-437e-9a52-2efdf0e392a4'
    Author = 'Brian Denicola'
    CompanyName = 'Denicolafamily'
    Copyright = '2020'
    RequiredModules = @('bjd.common.functions')
}

