version: '3'
  
tasks:
  up:
    desc: Creates Azure infrastructure and deploys application code
    cmds:
    - terraform -chdir=./infrastructure workspace new {{.REGION}} || true
    - terraform -chdir=./infrastructure workspace select {{.REGION}}
    - terraform -chdir=./infrastructure init
    - task: apply
    vars:
      REGION: '{{default "southcentralus" .CLI_ARGS}}'

  apply: 
    cmds:
    - terraform -chdir=./infrastructure apply -auto-approve -var "region={{.REGION}}"
    vars:
      REGION: '{{default "southcentralus" .CLI_ARGS}}'

  validate:
    cmds:
    - source ./scripts/setup-env.sh ; az rest --method get --url ${VALIDATION_URL}

  down:
    desc: Destroys Azure infrastructure and cleans up terraform state files
    cmds:
    - cd infrastructure ;
      rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - az group delete -n {{.RG}} --yes || true
    vars:
      RG: 
        sh: terraform -chdir=./infrastructure output -raw APP_RESOURCE_GROUP