name: Start Azure VMs

on:
  schedule:
    - cron: "15 5 * * *"
  workflow_dispatch:

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

jobs:
  BuildLinuxImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - uses: azure/login@v2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
                az vm start --ids $(az vm list --query "[].id" -o tsv)
